#!/bin/bash

usage() {
    cols=$(tput cols || echo 80)
    cat <<EOF | fmt -sw $((cols < 80 ? cols : 80))
usage of "$0"
A small utility to link and copy files across the system (a more general system that can be used to manage dotfiles)

options:
    -h, --help	Show this help
    --status    Shows currently tracked scripts

directives:
    A directive starts with the keyword "[Script]", this can be placed for example inside a line comment. Then must follow one of the following directives

    "[Script] @Link TARGET"
        Link a script file to a target destination. Creates missing folders.

    "[Script] @Copy TARGET"
        Copy a script file to a target destination, removing the copy declaration. Creates missing folders.

    patterns:
        The following variables are expanded inside directives arguments.

        Pattern   | Description
        ----------------------------------------
        ~         | home folder
        %f        | current script base name
        %r        | current script relative path
        %p        | current script absolute path
EOF
}

# Setup

# This file stores all tracked files (just for reference)
SCRIPT_STORE="$HOME/.cache/scripts-store"

mkdir -p "$(dirname "$SCRIPT_STORE")"
touch "$SCRIPT_STORE"

# Basic options

if [[ "$1" = '--help' || "$1" = '-h' ]]; then
	usage
	exit 0
fi

if [[ "$1" = '--status' || "$1" = '-s' ]]; then
	printf 'Current Setup:\n'
	cat "$SCRIPT_STORE"
	exit 0
fi

# Cache

finalize_store() {
	cat "$SCRIPT_STORE" | sort | uniq > "/tmp/scripts-store"
	cat "/tmp/scripts-store" > "$SCRIPT_STORE"
}

# Directives

directive_link() {
	# create the target path if missing
	mkdir -p "$(dirname "$2")"

	scriptRealpath="$(realpath "$1")"
	# link the script to the target path
	ln -sf "$scriptRealpath" "$2"

	printf '%s -> %s (link)\n' "$2" "$scriptRealpath" >> "$SCRIPT_STORE"
	printf 'Linked "%s" to "%s"\n' "$2" "$1"
}

directive_copy() {
	# create the target path if missing
	mkdir -p "$(dirname "$2")"

	scriptRealpath="$(realpath "$1")"
	# copy file to target skipping lines with the "[Script]" directive
	grep -v -F '[Script]' "$scriptRealpath" > "$2"

	printf '%s -> %s (copy)\n' "$2" "$scriptRealpath" >> "$SCRIPT_STORE"
	printf 'Copied "%s" from "%s"\n' "$2" "$1"
}

# Parse recursively current folder

grep --exclude=setup --exclude=README.md -r -F '[Script]' . | \
while read scriptDeclaration; do
	scriptFile="$(echo "$scriptDeclaration"| cut -d ':' -f 1)"
	scriptDirective="$(echo "$scriptDeclaration"| sed -E 's|(.*)\[Script\] ||g')"

	scriptCommand="$(echo "$scriptDirective" | sed -E 's|.+?@(\w+).+|\1|')"
	scriptArgs="$(echo "$scriptDirective" | sed -E 's|@\w+ (.+)|\1|')"

	scriptArgsEvaluated="$(echo "$scriptArgs" | \
		sed -E "s:~:$HOME:g" | \
		sed -E "s:%f:$(basename "$scriptFile"):g" | \
		sed -E "s:%r:$scriptFile:g" | \
		sed -E "s:%p:$(realpath "$scriptFile"):g" \
	)"

	case "$scriptCommand" in
		Link)
			directive_link "$scriptFile" "$scriptArgsEvaluated"
			;;
		Copy)
			directive_copy "$scriptFile" "$scriptArgsEvaluated"
			;;
	esac
done

finalize_store
